# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CFPhotoBrowseDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CFPhotoBrowseDemio
  pod 'SDWebImage', '~>3.8'

  target 'CFPhotoBrowseDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CFPhotoBrowseDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
